import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { PostHogProvider } from "./providers/posthog";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="preload"
        href="/fonts/Satoshi-Black.woff2"
        as="font"
        type="font/woff2"
        crossOrigin="anonymous"
      />
      <body className={` `}>
        <div className="lg:px-24 sm:px-5">
          <PostHogProvider>{children}</PostHogProvider>
        </div>
      </body>
    </html>
  );
}
